### PR TITLE
Updated typo for the index.ts example.

### PR DESCRIPTION
**Pull request by Jason-Terry**
`app.execute();`

Corrected the call to app.execute() in index.ts

See the issue here.

https://github.com/microsoft/web-build-tools/issues/1287

### CODE REVIEW

**Comment by octogonz** [comment]
Thanks for fixing! That example definitely would cause confusion

**Comment by octogonz** [comment]
@Jason-Terry could you run `rush change` on your branch?

**Comment by Jason-Terry** [comment]
> @Jason-Terry could you run `rush change` on your branch?

Of course, I need to clone it to my machine to run that correct?

**Comment by Jason-Terry** [comment]
Welp, that was embarrassing. I hope I did this correctly.

**Comment by octogonz** [comment]
Docs are here: https://rushjs.io/pages/developer/everyday_commands/

**Comment by octogonz** [comment]
(also don't forget to commit+push the change file)

**Comment by Jason-Terry** [comment]
Okay, I think I got it now. That was exciting for a one-line edit of documentation, haha.

**Comment by iclanton** [comment]
Strange that `rush change` had you create a changefile for every project. @Jason-Terry - What platform are you running? Did `rush change` give you any warnings or errors?

**Comment by Jason-Terry** [comment]
No warnings or errors. I am on Windows 10. I ran rush change from within
the top level folder of the main project, would that be why.

**Comment by halfnibble** [comment]
Did we merge some other changes into master without a rush change? Let me know if you think it'd be worth trying to replicate this.

**Comment by octogonz** [comment]
@halfnibble I can repro this problem by doing the following steps:
1. Clone https://github.com/Jason-Terry/web-build-tools
2. Switch to the **patch-2** branch:
    `git checkout -f -B patch-2 remotes/origin/patch-2`
3.  Rollback the `rush change`:
    `git reset --hard ab64f2d67e0a90cca544d3b1078e2be611131638`
4. Run `rush change`

The output looks like this:
```
Rush Multi-Project Build Tool 5.7.1 - https://rushjs.io

Starting "rush change"

Unable to find a git remote matching the repository URL (undefined). Detected changes are likely to be incorrect.
Target branch is origin/master

@microsoft/web-library-build
? Describe changes, or ENTER if no changes:
```

The [Unable to find a git remote matching the repository URL](https://github.com/microsoft/web-build-tools/blob/d21ed494711a891eb8631999d66bb423e397ff3c/apps/rush-lib/src/utilities/VersionControl.ts#L114) warning is telling us why the diff was computed incorrectly.

@iclanton  you worked on that code recently.  Do you know why this is happening?  Are people required to manually add `https://github.com/Microsoft/web-build-tools` as a remote for their GitHub forked repo?  If so, we should communicate that more clearly somehow.

**Pull request merged**
