### PR TITLE
[rush-lib] Fix typo in error message

### PR DESCRIPTION
**Pull request by smfoote**

### CODE REVIEW

**Comment by iclanton** [comment]
Approved.

You're missing a changefile. Run `rush change` to create one.

**Comment by smfoote** [comment]
I'm new to rush. When I try to run `rush change` I get "No change file is needed." Do I need to be on a branch other than master to create the change file?

**Comment by smfoote** [comment]
I _think_ I figured it out (used the previous commit as the branch option). Let me know if the change file doesn't look right.

**Comment by iclanton** [comment]
Yup - that's right.

Rush figures out which projects need a changefile by diffing the current branch against master, so you need to be on your feature branch when you run `rush change`.

**Pull request merged**
