### PR TITLE
[api-documenter] Add do not edit comment

### PR DESCRIPTION
**Pull request by skaapgif**
Many code bases consist of both written and generated documentation. This PR adds a "Do not edit this file" header similar to https://github.com/Microsoft/web-build-tools/blob/master/apps/api-extractor/src/generators/ReviewFileGenerator.ts#L42

### CODE REVIEW

**Comment by octogonz** [comment]
We should make the wording of the message more consistent with the report file message, but otherwise looks good to me

**Comment by skaapgif** [comment]
What about:
> Do not edit this file. It is documentation generated by [API Documenter](https://api-extractor.com/).

?

**Comment by octogonz** [comment]
Sure, that's a little more concise. :-)

**Comment by octogonz** [comment]
@skaapgif I fixed the message and removed the hyperlink (since markup isn't really valid inside an HTML comment).

**Comment by octogonz** [comment]
This fix was published with API Documenter beta release 7.0.49

**Comment by skaapgif** [comment]
Awesome, thanks :+1:

**Pull request merged**
