### PR TITLE
[load-themed-styles] Update TSDoc for loadedThemedStylesPath getter

### PR DESCRIPTION
**Pull request by Markionium**
The getter had the same comment as the setter :)

### CODE REVIEW

**Comment by iclanton** [comment]
You need a changefile as well. Just run `rush change` in your console.

**Comment by Markionium** [comment]
Thought i could do it online ;) Cloned it and added the file!

**Comment by iclanton** [comment]
Approved!

**Comment by iclanton** [comment]
:shipit:

**Pull request merged**
