### PR TITLE
Fixing GCB's schema validation.

### PR DESCRIPTION
**Pull request by iclanton**

### CODE REVIEW

**Comment by pgonzal** [comment]
This is the thing I'm trying to groom for **node-core-library**:

https://github.com/Microsoft/web-build-tools/blob/master/apps/rush-lib/src/utilities/JsonSchemaValidator.ts

It has unit tests.

**Comment by iclanton** [comment]
Extracting the validator from Rush-lib is going to be a bigger work item than I think this is worth. Let's just go with this small fix.

**Comment by pgonzal** [comment]
I'm cool with that. Consider me as verbally signed off
________________________________

**Comment by iclanton** [comment]
Approved

**Pull request merged**
