### PR TITLE
The install and the generate actions should run link automatically

### PR DESCRIPTION
**Pull request by nickpape-msft**
After running install or generate, we almost always want to run `rush link`. We should automatically do this.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/web-build-tools/134)

### CODE REVIEW

**Comment by iclanton** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/microsoft/web-build-tools/134#-KfJSfVyh6FaZJ88oOBR:-KfJSfVyh6FaZJ88oOBS:b6nm82a) (no related file):*
Can we include a `--nolink` parameter if we're going to do this?

---

*[rush/rush/src/actions/GenerateAction.ts, line 204 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/134#-KfJSYBl9l1RU8jlN9-6:-KfJSYBl9l1RU8jlN9-7:bijd2qt) ([raw file](https://github.com/microsoft/web-build-tools/blob/8ffa1def3652a7eb3043165ae9216c5ca759e12e/rush/rush/src/actions/GenerateAction.ts#L204)):*
> ```XML
>     console.log(os.EOL + colors.green(`Rush generate finished successfully. (${stopwatch.toString()})`));
> 
>     const linker: LinkAction = new LinkAction(this._parser);
> ```

I'd call the instance `linkAction`.

---

*[rush/rush/src/actions/InstallAction.ts, line 169 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/134#-KfJSc_SX7ZBSTLlMN6b:-KfJSc_SX7ZBSTLlMN6c:brhumzt) ([raw file](https://github.com/microsoft/web-build-tools/blob/8ffa1def3652a7eb3043165ae9216c5ca759e12e/rush/rush/src/actions/InstallAction.ts#L169)):*
> ```XML
>     console.log(colors.green(`The common NPM packages are up to date. (${stopwatch.toString()})`));
> 
>     const linker: LinkAction = new LinkAction(this._parser);
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/134)*

**Comment by nickpape-msft** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/microsoft/web-build-tools/134#-KfJSfVyh6FaZJ88oOBR:-KfN4ydxM-skJk07aHHw:bgx409x) (no related file):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Can we include a `--nolink` parameter if we're going to do this?
</blockquote></details>

That sounds like a decent idea (although I don't think it will be used). It's trivial to add.

---

*[rush/rush/src/actions/GenerateAction.ts, line 204 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/134#-KfJSYBl9l1RU8jlN9-6:-KfN5pbKR1f1Ciyht3TQ:b-896fix) ([raw file](https://github.com/microsoft/web-build-tools/blob/8ffa1def3652a7eb3043165ae9216c5ca759e12e/rush/rush/src/actions/GenerateAction.ts#L204)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

I'd call the instance `linkAction`.
</blockquote></details>

Done.

---

*[rush/rush/src/actions/InstallAction.ts, line 169 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/134#-KfJSc_SX7ZBSTLlMN6b:-KfN5qLC9d-jqVFYxQSx:b-896fix) ([raw file](https://github.com/microsoft/web-build-tools/blob/8ffa1def3652a7eb3043165ae9216c5ca759e12e/rush/rush/src/actions/InstallAction.ts#L169)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/134)*

**Comment by nickpape-msft** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/134)*

**Comment by nickpape-msft** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/134)*

**Pull request merged**
