### PR TITLE
Add a --transaction flag to restore 'transactional' publishing

### PR DESCRIPTION
**Pull request by ThomasMichon**
Added a `--transaction` flag for `rush publish` which restores the original behavior of failing the Publish floe if a single package failed to publish, ensuring that the change files are not deleted, and the version updates are not committed back to the target branch.
This provides a better opportunity for recovery from a previously-failed publish than having a subsequent `rush publish` call silently succeed without actually publishing new changes.

### CODE REVIEW

**Comment by octogonz** [comment]
@ThomasMichon what happens if you're publishing 20 packages, and after the first 13 have been successfully published, the operation fails due to a network timeout?  

The model is supposed to be that you (1) use `rush version` to create a Git commit that corresponds to the state that will be published, (2) build that (and possibly save it as an artifact), and then (3) run `rush publish` to publish that well-defined state.  This makes step 3 an idempotent operation that can be retried as many times as necessary until it fully succeeds.

Prior to the introduction of `rush version`, in the old days `rush publish` was a single operation that tried to do all these steps, but that usage is deprecated because it can malfunction if something fails partway through:  Suppose the publishing fails and you have NOT committed your version bumps (e.g. 1.2.3 --> 1.2.4).  Then when you retry the operation later, if more changes were committed to the branch in the meantime, then the new `1.2.4` may have different stuff in it.  That would be very bad if thirteen of the 1.2.4 packages came from a different Git commit than the other seven packages.

@iclanton

**Comment by ThomasMichon** [comment]
I typically see two scenarios here:

**The timeout scenario:**

1. Package `A` depends on `B` and `C`. User makes changes to `C`.
2. Kick off publish build with change.json file pending for `C`.
3. `rush build` completes, `rush publish --publish` starts.
4. `rush publish` bumps version of `C` according to change file.
5. Since `A` depends on `C`, `C` receives a version bump.
6. Run `npm publish` on `C`
7. Job timeout

At this point, the user's changes to `C` have been published, but a corresponding version of `A` which consumes `C` has not. And the change file was never deleted, nor were the `package.json` files for either `A` or `C` updated in source.

Oh well, kick another Publish job.
But wait, since the last run, someone *else* has checked in a change to `C`!

Before my PR:
1. Kick off publish build with two change.json files pending for `C`.
2. `rush build` completes, `rush publish --publish` starts
3. Both change files pending for `C` result in the same version bump for `C`
4. Since `C` was updated, `A` gets a version bump
5. `npm publish` runs for `C`. Since a corresponding version has already been published, `npm publish` skips `C`.
6. `npm publish` runs for `A`.
7. Tags are committed back for the versions of `C` and `A`
8. `package.json` files committed to source and change.json files are deleted.

Now both the change files for `C` are deleted, indicating those changes made it into the version. But the second user's changes aren't actually in that package!

With my PR:
5. `npm publish` runs for `C`. Since a corresponding version has already been published, `rush publish` terminates.
6. The entire Publish build fails.
7. A build administrator runs a script which updates all `package.json` files to reflect the last versions of each package that were published.
8. The Publish build is run again, two change.json files still pending for `C`.
9. New package versions are generated *above* those of last time.
10. `npm publish` succeeds because there are no collisions
11. Tags are written, `package.json` files are updated, and change.json files are deleted.

Both user's changes are in the newest releases of `C` and `A` correctly points to that new version. Sure, a version of `A` is missing from the timeline, but at least we got back to a good state.

**The conflict scenario:**

1. Package `A` depends on `B` and `C`. User makes changes to `C`.
2. Kick off publish build with change.json file pending for `C`.
3. `rush build` completes, `rush publish --publish` starts.
4. `rush publish` bumps version of `C` according to change file.
5. Since `A` depends on `C`, `C` receives a version bump.
6. Run `npm publish` on `C`
7. Run `npm publish` on `A
8. Delete change.json files
9. Commit deletions and `package.json` updates
10. `git push` fails due to conflict.

Here, the changes have all been published, but source doesn't reflect that.

Of course, another user checks in a change to `C`, and that triggers another Publish build.
But again, that change to `C` is never published, because it generates the same, original version bump, which already has a corresponding package published. The change.json files are deleted, the tags are written, and it looks to everyone that the second change was published until you discover it isn't in the actual package!

With my change, yes, the build admin has to run a 'fixer' script, but at least the current failure state is easily deducted and corrected via automation. Without my change, it looks like everything succeeded unless you crack open the `changelog.json` file in the actual package and see that it doesn't reflect the last change.json file that was deleted!

I believe the change made to check for an existing package has created more trouble, rather than reduced it, and I'm trying to get back into a healthy state, even if we both know that the overall Publish job should be better!

As an aside, even with `rush version`, I'd still want it not to `git push` if the `npm publish` task failed anywhere. And `rush version` currently doesn't write tags. With those two missing behaviors, it's not sufficient for our current flow.

**Comment by octogonz** [comment]
@ThomasMichon  when you say:

> 5. Since `A` depends on `C`, `C` receives a version bump.

I assume you mean 

> 5. Since `A` depends on `C`, `A` receives a version bump.

right?

**Comment by octogonz** [comment]
@ThomasMichon 
> As an aside, even with `rush version`, I'd still want it not to `git push` if the `npm publish` task failed anywhere. And `rush version` currently doesn't write tags. With those two missing behaviors, it's not sufficient for our current flow.

It seems like you're missing my main point.  The design should be:

1. Commit something to Git that describes a version set to be published
2. Run `rush publish` (possibly with retries) until that version set is published successfully.

There is a possibility that someone could come along and merge more stuff into master between #1 and #. A build administrator runs a script which updates all package.json files to reflect the last versions of each package that were published.

You're describing how Rush used to work in the old days.  We would regularly have a problem where somebody would notice that stuff wasn't getting published.  What happened? The system was trying to publish 55 packages and failed due to a timeout after publishing 26 of them, and the CI job could not recover from this.  So then a person would have to manually fiddle around with all the package.json files and get the job running again.  This takes time, so they'd need to find time, during which the entire pipeline was in a broken state.  It's a bad experience.

It is completely possible for Rush's publishing job to recover from intermittent network failures and finish publishing the rest of the packages.  The current design is far from ideal, but it does accomplish that goal, if you configure your workflow correctly.  From your description, I feel like your workflow is fundamentally incorrect.

@iclanton FYI

**Comment by iclanton** [comment]
Tabling this for now.

**Pull request closed without merging**
