### PR TITLE
Support add suffix to version.

### PR DESCRIPTION
**Pull request by qinweiz**
Suffix is different from pre-release. Adding a suffix only appends the suffix to existing versions and does not bump up versions.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/web-build-tools/143)

### CODE REVIEW

**Comment by iclanton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[rush/rush/src/actions/PublishAction.ts, line 138 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUUVwb-g8yDLEfC07:-KgDUUVwb-g8yDLEfC08:bq5chcu) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/actions/PublishAction.ts#L138)):*
> ```XML
>     if (this._includeAll.value && this._publish.value) {
>       this._publishAll(allPackages);
>     } else {
> ```

Why does this only happen in the `else` case?

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 6 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUbYn5JMTcTEWXQH6:-KgDUbYoFwj4iXMViLBU:bqk34yg) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L6)):*
> ```XML
>   constructor(private _prereleaseName?: string, private _suffixName?: string) {
>     if (_prereleaseName && _suffixName) {
>       throw new Error('Pre-release name and suffix cannot be provided at the same time.');
> ```

Constructors should never throw. Do the validation before construction.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 8 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUxdxEnKAzG_1nUMr:-KgDUxdxEnKAzG_1nUMs:bl5c3z9) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L8)):*
> ```XML
>       throw new Error('Pre-release name and suffix cannot be provided at the same time.');
>     }
>     this._name = !!_prereleaseName ? _prereleaseName : _suffixName;
> ```

Why not just say `this._name = _prereleaseName || _suffixName;`?

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 11 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUwGnjHYk83mWVB0F:-KgDUwGnjHYk83mWVB0G:b-7y99ut) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L11)):*
> ```XML
>   }
> 
>   public hasValue(): boolean {
> ```

Why not make this a getter?

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 15 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUpDlIvvAROpAiC2J:-KgDUpDlIvvAROpAiC2K:brhumzt) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L15)):*
> ```XML
>   }
> 
>   public isPrerelease(): boolean {
> ```

Same here.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 19 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUt6eHyMh_mkSca-X:-KgDUt6foIVMgoV6HKwb:brhumzt) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L19)):*
> ```XML
>   }
> 
>   public isSuffix(): boolean {
> ```

Same here.

---

*[rush/rush/src/utilities/test/PublishUtilities.test.ts, line 297 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDVDC_vQJv35-BtiY8:-KgDVDC_vQJv35-BtiY9:b-fuhp06) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/test/PublishUtilities.test.ts#L297)):*
> ```XML
>   });
> 
>     it('can update root with patch change for adding version suffix', () => {
> ```

Indentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/143)*

**Comment by qinweiz** [comment]
*[rush/rush/src/utilities/test/PublishUtilities.test.ts, line 297 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDVDC_vQJv35-BtiY8:-KgLShqwPWYVAbVKPcA9:bt2vr1b) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/test/PublishUtilities.test.ts#L297)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/143)*

**Comment by qinweiz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[rush/rush/src/actions/PublishAction.ts, line 138 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUUVwb-g8yDLEfC07:-KgLQnTMWrGtp_WiunH1:b86sl1a) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/actions/PublishAction.ts#L138)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Why does this only happen in the `else` case?
</blockquote></details>

It is only needed when we are publishing changed packages. PublishAll does not change versions.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 6 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUbYn5JMTcTEWXQH6:-KgLROCqNUArHrYadElo:b-4mnr04) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L6)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Constructors should never throw. Do the validation before construction.
</blockquote></details>

Constructors can throw... I want to wrap the logic inside this class. It is for containing all the logic related to the suffix pre-release inside.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 8 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUxdxEnKAzG_1nUMr:-KgLSC9ZpTSdwY9daZBo:b-lx4fjp) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L8)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Why not just say `this._name = _prereleaseName || _suffixName;`?
</blockquote></details>

Fixed.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 11 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUwGnjHYk83mWVB0F:-KgLSRmGAUVdIqc3Zz2P:b-lx4fjp) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L11)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Why not make this a getter?
</blockquote></details>

Fixed.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 15 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUpDlIvvAROpAiC2J:-KgLSSuYNCxWtB5gR5kq:bt2vr1b) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L15)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Fixed.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 19 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUt6eHyMh_mkSca-X:-KgLSU-zVvoPy1jjBais:b-886gsx) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L19)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/143)*

**Comment by iclanton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 6 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUbYn5JMTcTEWXQH6:-KgLX5lkkxEavjyc6eAN:b-j9px07) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L6)):*
<details><summary><i>Previously, qinweiz (QZ) wrote…</i></summary><blockquote>

Constructors can throw... I want to wrap the logic inside this class. It is for containing all the logic related to the suffix pre-release inside.
</blockquote></details>

It's generally considered bad practice have a constructor throw because it can be difficult to trace the exception and because object initialization is a "special" operation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/143)*

**Comment by iclanton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[rush/rush/src/utilities/PrereleaseToken.ts, line 6 at r1](https://reviewable.io:443/reviews/microsoft/web-build-tools/143#-KgDUbYn5JMTcTEWXQH6:-KgLYKKu0X9VBYiCFS4-:b-v5w2ad) ([raw file](https://github.com/microsoft/web-build-tools/blob/e1d148c680f71ef95fad0ecddbd154065abcd6c4/rush/rush/src/utilities/PrereleaseToken.ts#L6)):*
<details><summary><i>Previously, iclanton (Ian Clanton-Thuon) wrote…</i></summary><blockquote>

It's generally considered bad practice have a constructor throw because it can be difficult to trace the exception and because object initialization is a "special" operation.
</blockquote></details>

I guess this is fine, but it's something I've always been told not to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/143)*

**Comment by iclanton** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/web-build-tools/143)*

**Pull request merged**
