### PR TITLE
[api-documenter] Support more types for markdown

### PR DESCRIPTION
**Pull request by adventure-yunfei**
Support following api item kinds for markdown documenter:
- `namespace`
- `type` alias
- `function`

Should be pretty safe.

Updated:
- add one more `variable` type. 

And found a risk: from AE7, the document page uses `apiItem.getScopedNameWithinPackage()` as the title. When introducing namespace (and later local module re-export by `export * from './local';`), these names may not be proper. @pgonzal .

### CODE REVIEW

**Comment by pgonzal** [comment]
@adventure-yunfei thanks for contributing this PR!  Currently all of our team is away on Christmas vacation, so it may take me a little while to get this merged+published.  Thanks again!

**Comment by pgonzal** [comment]
> */

We can delete this old code

---
Refers to: apps/api-documenter/src/documenters/MarkdownDocumenter.ts:340 in beec75d. [](commit_id = beec75d3a5e57ebf99e7b72cb0a139882034fec3, deletion_comment = False)

**Comment by pgonzal** [comment]
> And found a risk: from AE7, the document page uses `apiItem.getScopedNameWithinPackage()` as the title. When introducing namespace (and later local module re-export by `export * from './local';`), these names may not be proper. @pgonzal .

I assume you're referring to titles such as `OuterNamespace.InnerNamespace.nestedFunction() function`?

In JavaScript, this really is the unambiguous correct name for the API item (since e.g. there could be many nested members called `nestedFunction`).  Currently we tend to document it this way, e.g. see [ffice.AddinCommands.Event interface](https://docs.microsoft.com/en-us/javascript/api/office/office.addincommands.event?view=office-js).

If you think there's a better way to present this, could you open a GitHub issue to propose that?  It might be a useful discussion.

**Comment by pgonzal** [comment]
I added a minor suggestion, but otherwise this looks good.  👍   (Sorry it took me a while to review this PR.)

**Comment by pgonzal** [comment]
> */

Fixed

---
In reply to: [452551291](https://github.com/Microsoft/web-build-tools/pull/1006#issuecomment-452551291) [](ancestors = 452551291)

---
Refers to: apps/api-documenter/src/documenters/MarkdownDocumenter.ts:340 in beec75d. [](commit_id = beec75d3a5e57ebf99e7b72cb0a139882034fec3, deletion_comment = False)

**Comment by pgonzal** [comment]
:shipit:

**Comment by pgonzal** [comment]
This was published as AE7 beta **api-documenter@7.0.12**

**Comment by pgonzal** [comment]
@adventure-yunfei FYI we have API Extractor t-shirts.  If you want one, [IM me on Gitter](https://gitter.im/pgonzal) 😄

**Comment by adventure-yunfei** [comment]
@pgonzal I'd like to, but there's a very long way between us~ Thanks for your kindness~

**Comment by pgonzal** [comment]
Up to you.  (We'd be fine with sending it in the mail.)

**Pull request merged**
