### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by apostolisms**

### CODE REVIEW

**Comment by iclanton** [comment]
Here's what this looks like rendered:

>## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##
>
>**Is this a feature or a bug?**
>
>**Please describe the actual behavior.**
>
>**If the issue is a bug, how can we reproduce it?**
>
>**What is the expected behavior?**
>
>**Please provide the tool version, Node.js version and OS.**

**Comment by iclanton** [comment]
How about this:

>## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##
>
>**Is this a feature or a bug?**
> - [ ] Feature
> - [ ] Bug
>
>**Please describe the actual behavior.**
>
>**If the issue is a bug, how can we reproduce it? Please provide repro steps or a link to a repro repository.**
>
>**What is the expected behavior?**
>
>**Please provide the tool version, Node.js version and OS.**
> - Tool:
> - Tool Version:
> - Node Version:
> - OS:

**Comment by octogonz** [comment]
https://github.com/microsoft/TypeScript/issues/new/choose

When you create a new issue for TypeScript, it gives you a choice between 3 templates.

Would it make sense for WBT to have separate templates for each project (e.g. Rush, API Extractor, or General)?  Then we could give additional project-specific guidance.  Maybe this could help prepopulate the title with the `[project-name]` prefix somehow.

**Comment by octogonz** [comment]
> **If the issue is a bug, how can we reproduce it? Please provide repro steps or a link to a repro repository.**

could maybe be improved to:

> **If the issue is a bug, how can we reproduce it?  Please provide detailed steps and include a GitHub branch if applicable.  Your issue will get resolved faster if you can make it easy to investigate.**

**Comment by apostolisms** [comment]
@octogonz good idea we can create custom templates per tool but if the layout/wording is not any different I am not sure if we gain a lot. One benefit is maybe the pre-populated title? I am fine either way. Let me know. 

This is how it looks like now: 

## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##
 
**Is this a feature or a bug?**

- [ ] Issue
- [ ] Bug

**Please describe the actual behavior.**

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

**Please provide the tool version, Node.js version and OS.**

* Tool: 
* Tool Version:
* Node Version: 
* OS:

**Pull request merged**
