### PR TITLE
Karma tests now fail the build.

### PR DESCRIPTION
**Pull request by dzearing**
Current behavior:

In non `--production` builds, failed tests in gcb-karma throw a warning and succeed the build.

New behavior:

In all flavors of builds, failed tests fail the build.

### CODE REVIEW

**Comment by pgonzal** [comment]
:clock1:

**Comment by dzearing** [comment]
@pgonzal Forgot about this. I'm pretty convinced there are no scenarios where failed tests should simply warn you and let you continue. If we want to keep build friction low, don't run tests in the inner loop and have a separate workflow (`npm run test`) for running the tests, so that the inner loop doesn't run them and that you need to explicitly run them.

**Comment by pgonzal** [comment]
@dzearing 
> I'm pretty convinced there are no scenarios where failed tests should simply warn you and let you continue.

Under our current semantics:
- Failed tests do NOT prevent you from recompiling all your projects (i.e. they do NOT block "rush build")
- Failed tests DO prevent you from merging your PR (i.e. they DO block "rush build --production")

That seems right to me.  Isn't your PR changing these semantics somehow?

**Comment by dzearing** [comment]
My suggestion is that if `rush build` is the inner loop workflow, it should avoid running tests. and that something like `rush run test` should run that.

**Comment by dzearing** [comment]
@pgonzal I've updated the PR to avoid changing any behavior without opting in. Is this ok? I'd like to get this merged so that I can reduce our build times by 10 minutes.

**Comment by pgonzal** [comment]
@dzearing 

Cool.  I think your scenario is interesting however.  At our next tools meeting, we'll discuss how this aligns with the inner loop for **sp-build-internal-web**, and why the two workflows are different.

> (Ideally we have some run command like lerna has which can execute a specific script.)

Actually, @nickpape is presenting a spec for this at 2pm today.  :-)  I'll send you an invite.

:shipit:

**Pull request merged**
