### PR TITLE
Preparing for rush publish.

### PR DESCRIPTION
**Pull request by iclanton**

### CODE REVIEW

**Comment by octogonz** [comment]
While revising the diff, I noticed that in PR #1062 we removed [a section of code](https://github.com/Microsoft/web-build-tools/commit/3c5ccff366028fa7fdfc1468d89f067690c94a3a#diff-20b3a43722f69a185c11d4d0291d91a0L194) that reports an error if the `"build"` command is missing:

```ts
      script = this._getScriptCommand('build');

      if (script === undefined) {
        // tslint:disable-next-line:max-line-length
        throw new Error(`The project [${this._rushProject.packageName}] does not define a 'build' command in the 'scripts' section of its package.json`);
      }
```

I'm not sure this was an intended feature change. Rush performs this validation to avoid mistakes, and the [docs](https://rushjs.io/pages/maintainer/add_to_repo/) mention it:

> * If certain projects don't need to be processed by `rush build`, you still need a `build` entry.  Set the value to an empty string (`""`) and Rush will ignore it.

We should test this, and if it changed, we should consider restoring the old behavior.

**Comment by wbern** [comment]
I think it should be opt-in. I have several nodejs packages that don't need building and it was a little weird to add an empty build script to them all.

**Comment by raygesualdo** [comment]
I agree with @wbern. Opt-in seems to be preferable. To maintain visibility, perhaps Rush could print out a message saying that certain packages weren't build if there's no build command.

**Comment by octogonz** [comment]
If there's a consensus to remove this check, I'm fine with that. But @iclanton we should note the change in CHANGLOG.md and remember to update the web site docs.

**Comment by ScottHysom** [comment]
For the default case, the functionality actually shouldn't have changed, even with those lines of code removed. In the whole change, the evaluation of whether the build script exists is performed like any other script if `_ignoreMissingScript` is `false` (the default setting for `build`).

```
  private _getScriptToRun(): string {
    const script: string | undefined = this._getScriptCommand(this._commandToRun);

    if (script === undefined && !this._ignoreMissingScript) {
      // tslint:disable-next-line:max-line-length
      throw new Error(`The project [${this._rushProject.packageName}] does not define a '${this._commandToRun}' command in the 'scripts' section of its package.json`);
    }
```

**Comment by octogonz** [comment]
Thanks @ScottHysom for clarifying.  @iclanton let's include this test case just to be sure.

**Comment by ScottHysom** [comment]
Thank you @octogonz and @iclanton!

**Pull request merged**
