### PR TITLE
[api-extractor]: Upgrade typescript minor to 3.4

### PR DESCRIPTION
**Pull request by skaapgif**
Upgrades the typescript version used by `api-extractor` to analyze projects.

### CODE REVIEW

**Comment by octogonz** [comment]
FYI you are upgrading the compiler used to compiler API Extractor. If you want to upgrade the compiler that API Extractor uses when analyzing a project, that's this line:

https://github.com/Microsoft/web-build-tools/blob/5fcdc42baf2dab3a03f7608c6d7673e08eb4b2fd/apps/api-extractor/package.json#L41

**Comment by skaapgif** [comment]
@octogonz Thanks, I've changed the PR to correctly upgrade typescript.

**Comment by skaapgif** [comment]
I'm really battling with the rush build system here. @octogonz or @iclanton Can you offer some guidance for how I should go about upgrading api-extractor's typescript version?

**Comment by octogonz** [comment]
@iclanton maybe you could help with this?  It seems that API-Extractor-on-TypeScript  3.3.3333 is not able to analyze projects that build using **rush-stack-compiler-3.2**, whereas API-Extractor-on-TypeScript 3.1.6 did not encounter any such.

Here's an example error when building the **rushell** library (which uses **rush-stack-compiler-3.2**):

> Warning - [api-extractor] Warning: wbt/common/temp/node_modules/.registry.npmjs.org/typescript/3.2.4/node_modules/typescript/lib/lib.es2015.iterable.d.ts:43:6 - (TS2585) 'Symbol' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.

@iclanton I wonder if RSC should always invoke API Extractor using the `--typescript-compiler-folder` option.

We could probably solve this by upgrading all the WBT projects to a newer RSC, but this scenario is supposed to work. The whole idea is that we don't want to have to maintain separate API Extractor release branches for each TypeScript compiler release.

**Comment by octogonz** [comment]
> @iclanton I wonder if RSC should always invoke API Extractor using the `--typescript-compiler-folder` option.

Actually, it appears that we're already doing that:

[ApiExtractorRunner.ts](https://github.com/Microsoft/web-build-tools/blob/18b34857f4b77ddc58c769c7b2aeffab61efadf0/stack/rush-stack-compiler-shared/src/shared/ApiExtractorRunner.ts#L61)
```ts
          message.handled = true;
        },
        typescriptCompilerFolder: ToolPaths.typescriptPackagePath
      };
```

I'm going to update this PR and see if I can figure out what's going on.

**Comment by octogonz** [comment]
Weird...  I started over with a clean upgrade: API Extractor now uses typescript 3.4 for analysis, while API Extractor itself is still built using RSC 3.2.  It worked perfectly the first time.  The `typescriptCompilerFolder` feature seems to be working perfectly.  I'm not sure what we were doing wrong before, but... problem solved, so I'm not going to investigate it heheh.

**Comment by skaapgif** [comment]
Awesome 🎉

**Comment by octogonz** [comment]
This feature was published with the API Extractor beta release 7.0.41

**Pull request merged**
