### PR TITLE
[api-documenter] Add support for TypeScript constructors

### PR DESCRIPTION
**Pull request by raymondfeng**
This PR adds the ability to generate tsdocs for TypeScript constructors, such as:

```ts
class MyLoggere {
  /**
   * Create an instance of MyService
   * @param logLevel - Logging level
   */
   constructor(private logLevel: string) {
   }
}
```

### CODE REVIEW

**Comment by octogonz** [comment]
Thanks for fixing this!

**Comment by octogonz** [comment]
BTW @raymondfeng if you want a free API Extractor T-shirt, ping me on [Gitter](https://gitter.im/octogonz). ;-P

**Comment by octogonz** [comment]
This was published as API Documenter 7.2.1

**Comment by raymondfeng** [comment]
@octogonz Thank you for the quick turn-around.

**Pull request merged**
