### PR TITLE
[api-extractor] Support deep link (e.g. for property type)

### PR DESCRIPTION
**Pull request by adventure-yunfei**
(note: `rush build` and `rush change` is not executed yet.)

# What does this PR do.

This PR is trying to support deep link for property type (class member, interface member, ...).

E.g. for following `api.d.ts` inside `"demo"` package:
```typescript
export interface Bar {
}
export interface Foo {
    member: Bar;
}
```

api-extractor generates following part of api.json:
```json
{
      "members": [
        {
          "kind": "Interface",
          "name": "Bar",
          "members": [],
          "excerptTokens": [
            {
              "kind": "Content",
              "text": "export interface "
            },
            {
              "kind": "Reference",
              "text": "Bar",
              "reference": "demo#Bar"
            },
            {
              "kind": "Content",
              "text": " "
            }
          ],
        },
        {
          "kind": "Interface",
          "name": "Foo",
          "members": [
            {
              "kind": "PropertySignature",
              "name": "member",
              "excerptTokens": [
                {
                  "kind": "Reference",
                  "text": "member",
                  "reference": "demo#Foo.member"
                },
                {
                  "kind": "Content",
                  "text": ": "
                },
                {
                  "kind": "Reference",
                  "text": "Bar",
                  "reference": "demo#Bar"
                },
                {
                  "kind": "Content",
                  "text": ";"
                }
              ],
            }
          ],
          "excerptTokens": [
            {
              "kind": "Content",
              "text": "export interface "
            },
            {
              "kind": "Reference",
              "text": "Foo",
              "reference": "demo#Foo"
            },
            {
              "kind": "Content",
              "text": " "
            }
          ],
        }
      ]
}
```

And the api-documenter generatos the `demo.foo.md` as following:

```md
......
## Properties

|  <p>Property</p> | <p>Type</p> | <p>Description</p> |
|  --- | --- | --- |
|  <p>[member](./demo.foo.member.md)</p> | <p>[Bar](./demo.bar.md)</p> |  |
......
```

The type of property `member` of interface `Foo` can now be linked to interface `Bar` page.

# How it is done.

1. When generating api items in `ApiModelGenerator.ts`, record them for each `ts.Symbol`
2. When generating excerpt token for an api item, if an identifier is found, resolve its referring `ts.Symbol` and record.
3. After processing, with previous recorded info, update the excerpt token reference to the actual api item path **by tsdoc `DocDeclarationReference` node format**.

### Pending implementation

- handle the case that a symbol can have multiple declarations (`DocMemberReference.selector` field)
- test with different cases
- Support reference for un-exported local items and external package items.

### CODE REVIEW

**Comment by pgonzal** [comment]
@adventure-yunfei thanks for contributing this PR! I apologize that no one has looked at it yet. We are out of office for holidays this week and next week.  This PR review is somewhat involved, since it is a [planned feature](https://github.com/Microsoft/web-build-tools/blob/628ecb23e16638571db0ecc09b722714ddbe0b27/apps/api-extractor/src/api/mixins/Excerpt.ts#L8), but the design is not fully worked out yet.  I may not be able to give in depth feedback until I'm back in the office.

Briefly, the intended design was to rely on the [declaration reference](https://github.com/Microsoft/tsdoc/issues/9#issuecomment-424877057) concept from TSDoc.  (There are a bunch of notation examples [here](https://github.com/Microsoft/tsdoc/blob/master/spec/code-snippets/DeclarationReferences.ts).)  API Extractor's declaration references are generated using [ApiItem.canonicalReference](https://github.com/Microsoft/web-build-tools/blob/628ecb23e16638571db0ecc09b722714ddbe0b27/apps/api-extractor/src/api/items/ApiItem.ts#L92), and parsed using [ApiModel.resolveDeclarationReference()](https://github.com/Microsoft/web-build-tools/blob/628ecb23e16638571db0ecc09b722714ddbe0b27/apps/api-extractor/src/api/model/ApiModel.ts#L139). This notation handles multiple declarations such as overloaded functions and merged declarations.  As you mentioned, when dealing with symbols exported from an external package, there is a problem of determining the appropriate entry point.  The tentative plan was to solve this using the [tsdoc-metadata.json data file](https://github.com/Microsoft/web-build-tools/blob/628ecb23e16638571db0ecc09b722714ddbe0b27/apps/api-extractor/src/analyzer/PackageMetadataManager.ts#L64) which was proposed in [TSDoc RFC #7](https://github.com/Microsoft/tsdoc/issues/7#issuecomment-442271815).  It's a little involved, so we decided to tackle this after version 7 is released.  

If you want to help push this feature along, that would be much appreciated!

**Comment by adventure-yunfei** [comment]
@pgonzal thanks for explanation. I've noticed that tsdoc link is handled in api-extractor, but only for some cases now.  I'll dig into your tsdoc info first.

**Comment by pgonzal** [comment]
(I wasn't sure about the status of this PR, so I've tagged it as "**PR: Waiting for author**."  If you're ready for me to look at it again, please remove that tag and add "**PR: Ready for review**")

**Comment by adventure-yunfei** [comment]
I'll close this PR as there should be a better way.

Luckily I can use this code inside my own branch. I've found a way to support the local file module re-export. With this change the api-documenter generates a perfect api site for our own projects right now~

**Comment by adventure-yunfei** [comment]
@octogonz I've created a new version from latest mater and force-pushed the branch. I'm willing to reopen this PR.
The main change is to use tsdoc `DocDeclarationReference` format instead of `getScopedNameWithinPackage()` to represent the api item reference.

**Comment by octogonz** [comment]
Thanks!  I finally got PR https://github.com/Microsoft/web-build-tools/pull/1077 completed and merged (which was a somewhat big undertaking), so this week I'm going to try to clear through the backlog of other PRs.

**Comment by octogonz** [comment]
After building your branch, I noticed a problem with the .api.json for this declaration:

**build-tests/api-extractor-scenarios/src/circularImport2/IFile.ts**
```ts
import { IFolder } from "./IFolder";

/** @public */
export class IFile {
  containingFolder: IFolder;
}
```

The corresponding .api.json looks like this:
```js
{
  "kind": "Class",
  "canonicalReference": "(IFile:class)",
  "docComment": "/**\n * @public\n */\n",
  "excerptTokens": [
    {
      "kind": "Content",
      "text": "export declare class "
    },
    {
      "kind": "Reference",
      "text": "IFile",
      "reference": "api-extractor-scenarios#IFile"
    },
    {
      "kind": "Content",
      "text": " "
    }
  ],
  "releaseTag": "Public",
  "name": "IFile",
  "members": [
    {
      "kind": "Property",
      "canonicalReference": "(containingFolder:instance)",
      "docComment": "",
      "excerptTokens": [
        {
          "kind": "Reference",
          "text": "containingFolder",
          "reference": "api-extractor-scenarios#IFile.containingFolder"  // <--- seems incorrect
        },
        {
          "kind": "Content",
          "text": ": "
        },
        {
          "kind": "Reference",
          "text": "IFolder"  // <--- no "reference" field
        },
        {
          "kind": "Content",
          "text": ";"
        }
      ],
      "releaseTag": "Public",
      "name": "containingFolder",
      "propertyTypeTokenRange": {
        "startIndex": 2,
        "endIndex": 3
      },
      "isStatic": false
    }
  ],
  "implementsTokenRanges": []
},
```

If I get some time I'll see if I can debug it.  Sorry it's taken me a while to finally look at this PR -- I've been very focused on the AE7 release.

**Comment by adventure-yunfei** [comment]
> "reference": "api-extractor-scenarios#IFile.containingFolder"  // <--- seems incorrect
The path is the api item reference path, it's referring to the `IFile.containingFolder` item inside `api-extractor-scenarios` package. I would think it's correct.

> "text": "IFolder"  // <--- no "reference" field
This is indeed a mistake, `IFolder` is exported but not found for the reference token. Since the link between reference token and api item is the same ts symbol, I guess there may be an alias making them pointing to different symbol. I'll try to make time to check that (but currently I'm busy with my work, it may take some time.)

**Comment by adventure-yunfei** [comment]
@octogonz Sorry that I didn't have time to check this util now.
Confirmed that the second case `"text": "IFolder" // <--- no "reference" field` is caused by aliased symbol, and fixed in https://github.com/microsoft/web-build-tools/pull/1005/commits/8d9382f842ee7cbf904bfc97fb10858b7100827a .

**Comment by adventure-yunfei** [comment]
updated with some code optimization and "rush build" results.

**Comment by octogonz** [comment]
Cool, thanks for making these updates!  I will take a look as soon as I can.  (Lately we're having trouble keeping up with all the activity in this repo! 😁)

**Comment by octogonz** [comment]
The latest work on this feature is in PR https://github.com/microsoft/web-build-tools/pull/1337.  That PR is focused on the DocFX/Yaml target.  It does not yet address the Markdown target, but the approach will be the same.  

We will probably close this PR, but I'd like to study it first to make sure the work here isn't useful.

**Comment by octogonz** [comment]
@adventure-yunfei thanks for contributing this PR!  As discussed we've decided to close it in favor of @rbuckton's PR https://github.com/microsoft/web-build-tools/pull/1337, which expands on this idea with a more comprehensive solution.

**Pull request closed without merging**
